### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [dkandalov/katas#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by dkandalov** [comment]
Hi, thanks for the suggestion. It seems that you opened similar issues for many repositories though. Looks to me like a spam to promote the website you mentioned, not very nice :( 
(Especially considering that you opened the issue for repository which is not really a project and is not intended to be used by anyone.)
